### ISSUE TITLE
Yeni itemler

### ISSUE THREAD

**Issue by sozboke** [ManhattanProjectBIL481/dungeon-1#2]
3 Tane yeni item ekleyeceğim ve bu itemler rastgele bir yerde görünür durumda olacak bunları ayrı ayrı toplayınca özel damage ve heal özellikleri verecek 3'ünü de toplayınca bu sefer daha fazla bonus özellik karakterimize tanımlanacak(daha fazla damage daha fazla heal)

**Comment by cagdasgerede** [comment]
Açıklama az olmuş. Düzeltin.
